# Generated by Django 4.1.5 on 2023-02-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_alter_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
    ]
